name: Auto-merge PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Only run for trusted contributors
    if: github.actor == 'Marceswan' || github.actor == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash  # or 'merge' or 'rebase'

permissions:
    contents: write
    pull-requests: write